const express = require('express');
const router = express.Router();
const { register, login, getMe, updateProfile, getAuthConfig } = require('../controllers/authController');
const { protect } = require('../middleware/authMiddleware');
const { validateRegister, validateLogin } = require('../middleware/validators');
const { authLimiter } = require('../middleware/rateLimiter');
router.get('/config', getAuthConfig);
router.post('/register', authLimiter, validateRegister, register);
router.post('/login', authLimiter, validateLogin, login);
router.get('/me', protect, getMe);
router.put('/profile', protect, updateProfile);
module.exports = router;